version: "3.8"

volumes:
  mysql_data:

services:
  php74-mvc:
    container_name: ${COMPOSE_PROJECT_NAME}-php74-mvc
    build: ./php74
    volumes:
      - type: tmpfs
        target: /var/www/mvc/var
        tmpfs:
          size: 1048576 # 1 MB
        volume:
          nocopy: true
      - type: bind
        source: ../Worker
        target: /var/www/mvc

    restart: always
#    depends_on:
#      - mysql
    working_dir: /var/www/mvc/src
    environment:
      - PHP_XDEBUG_IDEKEY=PSTORM
      - PHP_XDEBUG_DEFAULT_ENABLE=0
      - PHP_XDEBUG_REMOTE_ENABLE=0
      - PHP_XDEBUG_REMOTE_AUTOSTART=0
      - PHP_XDEBUG_REMOTE_CONNECT_BACK=0
      - PHP_XDEBUG_PROFILER_ENABLE=0
      - PHP_XDEBUG_REMOTE_HOST=host.docker.internal
      - PHP_XDEBUG_REMOTE_PORT=9006
      - PHP_XDEBUG_REMOTE_MODE=req
      - PHP_IDE_CONFIG=serverName=MVC-CLI
      - COMPOSER_MEMORY_LIMIT=-1
    networks:
      - mvc-components-net

  nginx:
    container_name: ${COMPOSE_PROJECT_NAME}-nginx
    restart: always
    image: nginx:latest
    depends_on:
      - php74-mvc
    ports:
      - "${nginx_port_on_host}:80"
    links:
      - php74-mvc
    volumes:
      - "./nginx/logs:/var/log/nginx"
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./nginx/conf.d:/etc/nginx/conf.template:ro"
      - "../Worker:/var/www/mvc:ro"
    environment:
      - NGINX_PORT=80
      - PHP_FPM_PORT=9000

      - MVC_NGINX_HOST=${nginx_local_hostname_mvc}
      - MVC_NGINX_PORT=8081
      - MVC_FPM_HOST=${COMPOSE_PROJECT_NAME}-php74-mvc
      - MVC_PREFIX=mvc

      - TZ=UTC
    # command подменит в шаблоне входа переменные на значения из заданных переменных окружения
    command: /bin/bash -c "envsubst \"`for v in $$(compgen -v);do printf '$${%s} ' $$v;done`'\" < /etc/nginx/conf.template/mvc.conf > /etc/nginx/conf.d/mvc.conf && nginx -g 'daemon off;'"

    networks:
      - mvc-components-net

#  mysql:
#    container_name: ${COMPOSE_PROJECT_NAME}-mysql
#    image: "mysql/mysql-server:5.7.21"
#    restart: always
#    environment:
#      - MYSQL_ROOT_PASSWORD=devroot
#      - TZ=UTC
#    ports:
#      - "${mysql_port_on_host}:3306"
#    volumes:
#      - "mysql_data:/var/lib/mysql"
#      - "./mysql/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql"
#    networks:
#      - mvc-components-net

networks:
  mvc-components-net:
    name: mvc-components-net
    driver: bridge
    ipam:
      driver: default
